# Generated by Django 4.2.8 on 2024-01-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mngrname', models.CharField(max_length=100)),
                ('qualif', models.CharField(max_length=80)),
                ('imgmngr', models.ImageField(upload_to='pics')),
                ('descr', models.TextField()),
            ],
        ),
    ]
