# Generated by Django 4.2.8 on 2024-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotaskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='date',
            field=models.DateField(default='1993-04-15'),
            preserve_default=False,
        ),
    ]
