# Generated by Django 4.2.8 on 2024-01-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imge',
            new_name='img',
        ),
    ]
